### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by LeoLeBras** [baloran/koa-sequelize-graphql#2]
`Fetch API cannot load http://localhost:3000/graphql. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by baloran** [comment]
Done #3
